LOGGING:
  LOGGER_LEVEL: DEBUG
  LOGGING_FORMAT: '[%(asctime)s] - %(levelname)s - %(module)s - %(message)s'
DIRS:
  MODELS_DIR: models
  KP_DETECTORS_DIR: key_points_detectors
  LOADED_VIDEOS: loaded_videos
  STATIC_DIR: static
FILES:
  CLASSES_MAPPING: classes_mapping.json
ML_MODELS:
  MAIN_SLR: LSTM_ROTATION_AUG_98.ckpt
  KP_DETECTOR: pose_landmarker.task
DB:
  DB_NAME: slr.db
  VIDEOS_TABLE: sign_videos

